/* ============================================================================
   02_BlueTrack_Baseline_EtlLoads.sql

   BASELINE (D-195, 2026-10-09). One of the six scripts that replaced the
   numbered scripts 01-51 before the first release. It builds the schema those
   scripts left behind, in final form: later columns and constraints are part
   of each CREATE TABLE, and each procedure, view and function appears once,
   as its last version. The history of every change is in git and in
   Claude_Docs/Design_Decision-Register.md.

   Runs only against an EMPTY database (App/Migrator gives it one). A database
   built from the old scripts has these baseline scripts marked as applied by
   App/Migrator instead of running them (see its header).

   The dbo load side: the dimension and fact load procedures, the name-pattern
   functions they use (dbo.fn_MatchesNamePattern / fn_RegexSupported, D-186),
   account reconciliation, dim_date, and the reporting and Power BI views.
   usp_RunFullLoad, which calls these in order, is defined last, in
   06_BlueTrack_Baseline_WebLogic.sql, since it also runs the risk-scoring steps.
   ============================================================================ */

USE $DatabaseName$;
GO


/* ----------------------------------------------------------------------------
   Helper: standardize the self-hosted Yes/No-style NVARCHAR(5) flags to BIT.
   CONFIRM the actual literal values in your data before trusting this --
   the DDL only tells us the column is NVARCHAR(5), not whether the vault
   writes 'Yes'/'No', 'Y'/'N', or something else. Run:
     SELECT DISTINCT CAUDisabled FROM stg_sh_users;
   and adjust the CASE below if the literals differ.
---------------------------------------------------------------------------- */
CREATE OR ALTER FUNCTION ufn_YNToBit (@val NVARCHAR(10))
RETURNS BIT
AS
BEGIN
    RETURN CASE
        WHEN UPPER(LTRIM(RTRIM(@val))) IN ('YES','Y','TRUE','1') THEN 1
        WHEN UPPER(LTRIM(RTRIM(@val))) IN ('NO','N','FALSE','0') THEN 0
        ELSE NULL
    END;
END
GO


DECLARE @Regex BIT = CASE WHEN CAST(SERVERPROPERTY('ProductMajorVersion') AS INT) >= 17
                           AND (SELECT compatibility_level FROM sys.databases WHERE name = DB_NAME()) >= 170
                          THEN 1 ELSE 0 END;
DECLARE @RegexBranch NVARCHAR(400) = CASE WHEN @Regex = 1
    THEN N'IF @Mode = N''Regex'' RETURN CASE WHEN REGEXP_LIKE(@Name, @Value, ''i'') THEN 1 ELSE 0 END;'
    ELSE N'-- Regex needs SQL Server 2025 (compatibility level 170): never matches here.' END;

EXEC (N'CREATE OR ALTER FUNCTION dbo.fn_MatchesNamePattern (@Name NVARCHAR(500), @Mode NVARCHAR(10), @Value NVARCHAR(200))
RETURNS BIT
AS
BEGIN
    -- D-186: generated by 48_BlueTrack_DecommissionPatterns.sql. Case-insensitive.
    IF @Name IS NULL OR @Value IS NULL OR @Value = N'''' OR @Mode IS NULL OR @Mode = N''Off'' RETURN 0;
    DECLARE @Length INT = DATALENGTH(@Value) / 2;
    IF @Mode = N''Prefix'' RETURN CASE WHEN UPPER(LEFT(@Name, @Length)) = UPPER(@Value) THEN 1 ELSE 0 END;
    IF @Mode = N''Suffix'' RETURN CASE WHEN UPPER(RIGHT(@Name, @Length)) = UPPER(@Value) THEN 1 ELSE 0 END;
    ' + @RegexBranch + N'
    RETURN 0;
END');

DECLARE @SupportedSql NVARCHAR(200) = N'CREATE OR ALTER FUNCTION dbo.fn_RegexSupported () RETURNS BIT AS BEGIN RETURN '
    + CASE WHEN @Regex = 1 THEN N'1' ELSE N'0' END + N'; END';
EXEC (@SupportedSql);
GO

/* ============================================================================
   1. dim_location  (Self-Hosted only -- Privilege Cloud exports carry no
      location hierarchy in the files you supplied)
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_DimLocation
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');

    ;WITH SourceLocations AS (
        SELECT DISTINCT CAST(CAULocationID AS NVARCHAR(50)) AS SourceLocationId, CAULocationName AS LocationName
        FROM stg_sh_users WHERE CAULocationID IS NOT NULL
        UNION
        SELECT DISTINCT CAST(CAGLocationID AS NVARCHAR(50)), CAGLocationName
        FROM stg_sh_groups WHERE CAGLocationID IS NOT NULL
        UNION
        SELECT DISTINCT CAST(CASLocationID AS NVARCHAR(50)), CASLocationName
        FROM stg_sh_safes WHERE CASLocationID IS NOT NULL
    )
    MERGE dim_location AS tgt
    USING (SELECT @SelfHostedKey AS SourceSystemKey, SourceLocationId, LocationName FROM SourceLocations) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceLocationId = src.SourceLocationId
    WHEN MATCHED AND tgt.LocationName <> src.LocationName THEN
        UPDATE SET LocationName = src.LocationName
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, SourceLocationId, LocationName)
        VALUES (src.SourceSystemKey, src.SourceLocationId, src.LocationName);
END
GO

/* ============================================================================
   2. dim_platform  (Privilege Cloud only -- see schema notes: Self-Hosted's
      EVD export has no Platforms table)
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_DimPlatform
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');

    MERGE dim_platform AS tgt
    USING (
        SELECT @PrivCloudKey AS SourceSystemKey, PlatformID, Name AS PlatformName, Description,
               Active AS IsActive,
               -- normalize inconsistent casing observed in source ('regular' / 'Regular' / 'group')
               LOWER(LTRIM(RTRIM(PlatformType))) AS PlatformType
        FROM stg_pc_platforms
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.PlatformID = src.PlatformID
    WHEN MATCHED THEN
        UPDATE SET PlatformName = src.PlatformName, Description = src.Description,
                   IsActive = src.IsActive, PlatformType = src.PlatformType
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, PlatformID, PlatformName, Description, IsActive, PlatformType)
        VALUES (src.SourceSystemKey, src.PlatformID, src.PlatformName, src.Description, src.IsActive, src.PlatformType);
END
GO

/* ============================================================================
   3. dim_safe  (both sources)
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_DimSafe
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');

    -- Privilege Cloud
    MERGE dim_safe AS tgt
    USING (
        SELECT @PrivCloudKey AS SourceSystemKey, SafeUrlId, SafeName, SafeNumber, Description, Location,
               Creator AS CreatorUsername, OLACEnabled, CAST(ManagingCPM AS NVARCHAR(200)) AS ManagingCPM,
               VersionRetention, DayRetention, AutoPurge, Created AS CreatedDate, LastModified AS LastModifiedDate,
               CAST(NULL AS INT) AS LocationKey
        FROM stg_pc_safes
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SafeUrlId = src.SafeUrlId
    WHEN MATCHED THEN
        UPDATE SET SafeName = src.SafeName, SafeNumber = src.SafeNumber, Description = src.Description,
                   Location = src.Location, CreatorUsername = src.CreatorUsername, OLACEnabled = src.OLACEnabled,
                   ManagingCPM = src.ManagingCPM, VersionRetention = src.VersionRetention,
                   DayRetention = src.DayRetention, AutoPurge = src.AutoPurge,
                   CreatedDate = src.CreatedDate, LastModifiedDate = src.LastModifiedDate
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, SafeUrlId, SafeName, SafeNumber, Description, Location, CreatorUsername,
                OLACEnabled, ManagingCPM, VersionRetention, DayRetention, AutoPurge, CreatedDate, LastModifiedDate)
        VALUES (src.SourceSystemKey, src.SafeUrlId, src.SafeName, src.SafeNumber, src.Description, src.Location,
                src.CreatorUsername, src.OLACEnabled, src.ManagingCPM, src.VersionRetention, src.DayRetention,
                src.AutoPurge, src.CreatedDate, src.LastModifiedDate);

    -- Self-Hosted: no SafeUrlId in this source -- use CASSafeID (as string) as the natural key instead
    MERGE dim_safe AS tgt
    USING (
        SELECT @SelfHostedKey AS SourceSystemKey,
               CAST(s.CASSafeID AS NVARCHAR(300)) AS SafeUrlId,
               s.CASSafeName AS SafeName, CAST(s.CASSafeID AS INT) AS SafeNumber,
               CAST(NULL AS NVARCHAR(1000)) AS Description,
               s.CASLocationName AS Location, s.CASCreatedBy AS CreatorUsername,
               CAST(NULL AS BIT) AS OLACEnabled, CAST(NULL AS NVARCHAR(200)) AS ManagingCPM,
               s.CASYearlyVersions AS VersionRetention, s.CASObjectsRetentionPeriod AS DayRetention,
               CAST(NULL AS BIT) AS AutoPurge,
               CAST(s.CASCreationDate AS DATE) AS CreatedDate, CAST(NULL AS DATE) AS LastModifiedDate,
               loc.LocationKey
        FROM stg_sh_safes s
        LEFT JOIN dim_location loc ON loc.SourceSystemKey = @SelfHostedKey
                                   AND loc.SourceLocationId = CAST(s.CASLocationID AS NVARCHAR(50))
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SafeUrlId = src.SafeUrlId
    WHEN MATCHED THEN
        UPDATE SET SafeName = src.SafeName, Location = src.Location, CreatorUsername = src.CreatorUsername,
                   VersionRetention = src.VersionRetention, DayRetention = src.DayRetention,
                   CreatedDate = src.CreatedDate, LocationKey = src.LocationKey
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, SafeUrlId, SafeName, SafeNumber, Description, Location, CreatorUsername,
                OLACEnabled, ManagingCPM, VersionRetention, DayRetention, AutoPurge, CreatedDate, LastModifiedDate, LocationKey)
        VALUES (src.SourceSystemKey, src.SafeUrlId, src.SafeName, src.SafeNumber, src.Description, src.Location,
                src.CreatorUsername, src.OLACEnabled, src.ManagingCPM, src.VersionRetention, src.DayRetention,
                src.AutoPurge, src.CreatedDate, src.LastModifiedDate, src.LocationKey);
END
GO

/* ============================================================================
   4. dim_user  (both sources)
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_DimUser
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');

    -- Privilege Cloud
    MERGE dim_user AS tgt
    USING (
        SELECT @PrivCloudKey AS SourceSystemKey, UserID AS SourceUserId, Username, UserType,
               Source AS UserSource, ComponentUser, Email, FirstName, LastName,
               CAST(NULL AS INT) AS LocationKey
        FROM stg_pc_users
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceUserId = src.SourceUserId
    WHEN MATCHED THEN
        UPDATE SET Username = src.Username, UserType = src.UserType, UserSource = src.UserSource,
                   ComponentUser = src.ComponentUser, Email = src.Email, FirstName = src.FirstName, LastName = src.LastName
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, SourceUserId, Username, UserType, UserSource, ComponentUser, Email, FirstName, LastName)
        VALUES (src.SourceSystemKey, src.SourceUserId, src.Username, src.UserType, src.UserSource,
                src.ComponentUser, src.Email, src.FirstName, src.LastName);

    -- Self-Hosted
    MERGE dim_user AS tgt
    USING (
        SELECT @SelfHostedKey AS SourceSystemKey, CAST(u.CAUUserID AS NVARCHAR(100)) AS SourceUserId,
               u.CAUUserName AS Username, CAST(u.CAUUserTypeID AS NVARCHAR(100)) AS UserType,
               CASE WHEN u.CAUExternalInternal = 1 THEN 'Internal'
                    WHEN u.CAUExternalInternal = 2 THEN 'External'
                    ELSE NULL END AS UserSource,          -- decoded via CATextCodes type 4
               CAST(NULL AS BIT) AS ComponentUser,
               u.CAUBusinessEmail AS Email, u.CAUFirstName AS FirstName, u.CAULastName AS LastName,
               loc.LocationKey
        FROM stg_sh_users u
        LEFT JOIN dim_location loc ON loc.SourceSystemKey = @SelfHostedKey
                                   AND loc.SourceLocationId = CAST(u.CAULocationID AS NVARCHAR(50))
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceUserId = src.SourceUserId
    WHEN MATCHED THEN
        UPDATE SET Username = src.Username, UserType = src.UserType, UserSource = src.UserSource,
                   Email = src.Email, FirstName = src.FirstName, LastName = src.LastName, LocationKey = src.LocationKey
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, SourceUserId, Username, UserType, UserSource, ComponentUser, Email, FirstName, LastName, LocationKey)
        VALUES (src.SourceSystemKey, src.SourceUserId, src.Username, src.UserType, src.UserSource,
                src.ComponentUser, src.Email, src.FirstName, src.LastName, src.LocationKey);
END
GO

/* ============================================================================
   5. dim_group  (both sources)
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_DimGroup
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');

    -- Privilege Cloud
    MERGE dim_group AS tgt
    USING (
        SELECT @PrivCloudKey AS SourceSystemKey, GroupID AS SourceGroupId, GroupName, Description,
               Location, GroupType, CAST(DirectoryType AS NVARCHAR(100)) AS DirectoryType,
               CAST(NULL AS INT) AS LocationKey
        FROM stg_pc_groups
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceGroupId = src.SourceGroupId
    WHEN MATCHED THEN
        UPDATE SET GroupName = src.GroupName, Description = src.Description, Location = src.Location,
                   GroupType = src.GroupType, DirectoryType = src.DirectoryType
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, SourceGroupId, GroupName, Description, Location, GroupType, DirectoryType)
        VALUES (src.SourceSystemKey, src.SourceGroupId, src.GroupName, src.Description, src.Location, src.GroupType, src.DirectoryType);

    -- Self-Hosted
    MERGE dim_group AS tgt
    USING (
        SELECT @SelfHostedKey AS SourceSystemKey, CAST(g.CAGGroupID AS NVARCHAR(100)) AS SourceGroupId,
               g.CAGGroupName AS GroupName, g.CAGDescription AS Description, g.CAGLocationName AS Location,
               CASE WHEN g.CAGExternalInternal = 1 THEN 'Internal'
                    WHEN g.CAGExternalInternal = 2 THEN 'External'
                    ELSE NULL END AS GroupType,
               g.CAGLDAPDirectory AS DirectoryType,
               loc.LocationKey
        FROM stg_sh_groups g
        LEFT JOIN dim_location loc ON loc.SourceSystemKey = @SelfHostedKey
                                   AND loc.SourceLocationId = CAST(g.CAGLocationID AS NVARCHAR(50))
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceGroupId = src.SourceGroupId
    WHEN MATCHED THEN
        UPDATE SET GroupName = src.GroupName, Description = src.Description, Location = src.Location,
                   GroupType = src.GroupType, DirectoryType = src.DirectoryType, LocationKey = src.LocationKey
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (SourceSystemKey, SourceGroupId, GroupName, Description, Location, GroupType, DirectoryType, LocationKey)
        VALUES (src.SourceSystemKey, src.SourceGroupId, src.GroupName, src.Description, src.Location,
                src.GroupType, src.DirectoryType, src.LocationKey);
END
GO

/* ============================================================================
   8. bridge_group_membership  (Privilege Cloud only for now -- see table
   comment in the schema file for the Self-Hosted extension note)

   Confirmed against the real export: MemberID matches stg_pc_users.UserID
   for most rows, but built-in system users (Administrator, Backup,
   Auditor, Operator, DR, TelemetryUser, etc.) don't appear in the Users
   export and won't resolve here -- the INNER JOIN below silently excludes
   them rather than inserting a meaningless NULL UserKey row. That's
   expected, not a bug; uncomment the SELECT at the bottom of this proc to
   see exactly which members are being excluded on a given run.
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_GroupMembership
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @Today DATE = CAST(SYSUTCDATETIME() AS DATE);

    DELETE bgm FROM bridge_group_membership bgm
        JOIN dim_group g ON g.GroupKey = bgm.GroupKey
        WHERE g.SourceSystemKey = @PrivCloudKey;

    INSERT INTO bridge_group_membership (GroupKey, UserKey, MemberLevel, SnapshotDate)
    SELECT DISTINCT g.GroupKey, u.UserKey, gm.MemberLevel, @Today
    FROM stg_pc_groupmembers gm
    JOIN dim_group g ON g.SourceSystemKey = @PrivCloudKey AND g.GroupName = gm.RootGroupName
    JOIN dim_user u  ON u.SourceSystemKey = @PrivCloudKey AND u.SourceUserId = gm.MemberID
    WHERE gm.MemberType = 'User';   -- only direct User members are handled; a future export containing Group-type nested members would need group-to-group expansion, not covered here

    -- Diagnostic: uncomment to see members that didn't resolve to a dim_user row
    -- SELECT DISTINCT gm.RootGroupName, gm.MemberName, gm.MemberID
    -- FROM stg_pc_groupmembers gm
    -- LEFT JOIN dim_user u ON u.SourceSystemKey = @PrivCloudKey AND u.SourceUserId = gm.MemberID
    -- WHERE gm.MemberType = 'User' AND u.UserKey IS NULL;
END
GO


CREATE OR ALTER PROCEDURE usp_Load_FactAccount
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');
    -- D-186: accounts in a safe matching the ignored-safe pattern aren't
    -- imported; ones already in BlueTrack drop out of the source rows
    -- below, so the load flags them deleted (history kept).
    DECLARE @IgnoreMode NVARCHAR(10), @IgnoreValue NVARCHAR(200);
    SELECT @IgnoreMode = SafeIgnoreMode, @IgnoreValue = SafeIgnoreValue FROM web.app_config;

    -- ---- Privilege Cloud ----
    MERGE fact_account AS tgt
    USING (
        SELECT
            @PrivCloudKey AS SourceSystemKey,
            a.AccountID AS SourceAccountId, a.AccountName, a.Address, a.UserName,
            plat.PlatformKey, sf.SafeKey,
            a.SecretType, a.AutoManaged, a.CPMStatus, a.ManualReason,
            a.LastCPMModified AS LastCPMModifiedDate, a.LastReconciled AS LastReconciledDate,
            a.LastVerified AS LastVerifiedDate, a.RemoteAccessRestricted,
            ISNULL(a.Deleted, 0) AS IsDeleted, a.Created AS CreatedDate, a.Platform_LogonDomain AS PlatformLogonDomain
        FROM stg_pc_accounts a
        LEFT JOIN dim_platform plat ON plat.SourceSystemKey = @PrivCloudKey AND plat.PlatformID = a.PlatformID
        LEFT JOIN dim_safe sf ON sf.SourceSystemKey = @PrivCloudKey AND sf.SafeName = a.SafeName
        WHERE dbo.fn_MatchesNamePattern(a.SafeName, @IgnoreMode, @IgnoreValue) = 0
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceAccountId = src.SourceAccountId
    WHEN MATCHED THEN
        UPDATE SET AccountName = src.AccountName, Address = src.Address, UserName = src.UserName,
                   PlatformKey = src.PlatformKey, SafeKey = src.SafeKey, SecretType = src.SecretType,
                   AutoManaged = src.AutoManaged, CPMStatus = src.CPMStatus, ManualReason = src.ManualReason,
                   LastCPMModifiedDate = src.LastCPMModifiedDate, LastReconciledDate = src.LastReconciledDate,
                   LastVerifiedDate = src.LastVerifiedDate, RemoteAccessRestricted = src.RemoteAccessRestricted,
                   IsDeletedInSource = src.IsDeleted, PlatformLogonDomain = src.PlatformLogonDomain
    -- D-184: an account the export already marks as deleted is never added;
    -- one BlueTrack already has is kept and flagged (WHEN MATCHED above).
    WHEN NOT MATCHED BY TARGET AND src.IsDeleted = 0 THEN
        INSERT (SourceSystemKey, SourceAccountId, AccountName, Address, UserName, PlatformKey, SafeKey,
                SecretType, AutoManaged, CPMStatus, ManualReason, LastCPMModifiedDate, LastReconciledDate,
                LastVerifiedDate, RemoteAccessRestricted, IsDeleted, CreatedDate, PlatformLogonDomain)
        VALUES (src.SourceSystemKey, src.SourceAccountId, src.AccountName, src.Address, src.UserName,
                src.PlatformKey, src.SafeKey, src.SecretType, src.AutoManaged, src.CPMStatus, src.ManualReason,
                src.LastCPMModifiedDate, src.LastReconciledDate, src.LastVerifiedDate, src.RemoteAccessRestricted,
                src.IsDeleted, src.CreatedDate, src.PlatformLogonDomain)
    -- an account present in fact_account for this source but absent from the
    -- latest staging snapshot means it no longer exists in the vault -- flag it
    WHEN NOT MATCHED BY SOURCE AND tgt.SourceSystemKey = @PrivCloudKey THEN
        UPDATE SET IsDeletedInSource = 1;

    -- ---- Self-Hosted ----
    ;WITH PivotedAccounts AS (
        SELECT
            f.CAFSafeID, f.CAFFileID, f.CAFSafeName,
            CAST(f.CAFSafeID AS NVARCHAR(50)) + '_' + CAST(f.CAFFileID AS NVARCHAR(50)) AS SourceAccountId,
            f.CAFFileName AS AccountName,
            f.CAFCreationDate AS CreatedDate,
            f.CAFModificationDate AS LastCPMModifiedDate,
            f.CAFLastUsedDate AS LastVerifiedDate,
            -- D-184: deleted when CAFDeletionDate is a real date: after the
            -- epoch placeholder some versions write (1970-01-01, or 1900 /
            -- 0001 defaults), and not before the account was created.
            CASE WHEN f.CAFDeletionDate >= '19700102'
                      AND (f.CAFCreationDate IS NULL OR f.CAFDeletionDate >= f.CAFCreationDate)
                 THEN 1 ELSE 0 END AS IsDeleted,
            -- PLACEHOLDER property names -- confirm against stg_sh_objectproperties before trusting
            MAX(CASE WHEN op.CAOPObjectPropertyName = 'UserName' THEN op.CAOPObjectPropertyValue END) AS UserName,
            MAX(CASE WHEN op.CAOPObjectPropertyName = 'Address'  THEN op.CAOPObjectPropertyValue END) AS Address,
            MAX(CASE WHEN op.CAOPObjectPropertyName = 'PolicyID' THEN op.CAOPObjectPropertyValue END) AS PolicyID
        FROM stg_sh_files f
        LEFT JOIN stg_sh_objectproperties op
               ON op.CAOPFileId = f.CAFFileID AND op.CAOPSafeId = f.CAFSafeID
        WHERE f.CAFType = 2   -- 'Password' per dim_selfhosted_code (CodeType 12, CodeValue 2)
          AND dbo.fn_MatchesNamePattern(f.CAFSafeName, @IgnoreMode, @IgnoreValue) = 0
        GROUP BY f.CAFSafeID, f.CAFFileID, f.CAFSafeName, f.CAFFileName,
                 f.CAFCreationDate, f.CAFModificationDate, f.CAFLastUsedDate, f.CAFDeletionDate
    )
    MERGE fact_account AS tgt
    USING (
        SELECT @SelfHostedKey AS SourceSystemKey, p.SourceAccountId, p.AccountName, p.Address, p.UserName,
               plat.PlatformKey, sf.SafeKey, p.CreatedDate, p.LastCPMModifiedDate, p.LastVerifiedDate, p.IsDeleted
        FROM PivotedAccounts p
        LEFT JOIN dim_safe sf ON sf.SourceSystemKey = @SelfHostedKey AND sf.SafeUrlId = CAST(p.CAFSafeID AS NVARCHAR(300))
        LEFT JOIN dim_platform plat ON plat.SourceSystemKey = @SelfHostedKey AND plat.PlatformID = p.PolicyID  -- will stay NULL until a Self-Hosted platform reference exists (see schema notes)
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceAccountId = src.SourceAccountId
    WHEN MATCHED THEN
        UPDATE SET AccountName = src.AccountName, Address = src.Address, UserName = src.UserName,
                   PlatformKey = src.PlatformKey, SafeKey = src.SafeKey,
                   LastCPMModifiedDate = src.LastCPMModifiedDate, LastVerifiedDate = src.LastVerifiedDate,
                   IsDeletedInSource = src.IsDeleted
    WHEN NOT MATCHED BY TARGET AND src.IsDeleted = 0 THEN
        INSERT (SourceSystemKey, SourceAccountId, AccountName, Address, UserName, PlatformKey, SafeKey,
                CreatedDate, LastCPMModifiedDate, LastVerifiedDate, IsDeleted)
        VALUES (src.SourceSystemKey, src.SourceAccountId, src.AccountName, src.Address, src.UserName,
                src.PlatformKey, src.SafeKey, src.CreatedDate, src.LastCPMModifiedDate, src.LastVerifiedDate, 0)
    WHEN NOT MATCHED BY SOURCE AND tgt.SourceSystemKey = @SelfHostedKey THEN
        UPDATE SET IsDeletedInSource = 1;

    -- D-185: IsDeleted -- the flag every list, report and view filters on --
    -- is deleted in CyberArk OR deleted in BlueTrack (web.account_deletion),
    -- so a BlueTrack delete survives the nightly load and an undelete
    -- returns the account to whatever CyberArk says.
    UPDATE fa
    SET IsDeleted = CASE WHEN fa.IsDeletedInSource = 1 OR ad.AccountKey IS NOT NULL THEN 1 ELSE 0 END
    FROM fact_account fa
    LEFT JOIN web.account_deletion ad ON ad.AccountKey = fa.AccountKey
    WHERE fa.SourceSystemKey IN (@PrivCloudKey, @SelfHostedKey)
      AND fa.IsDeleted <> CASE WHEN fa.IsDeletedInSource = 1 OR ad.AccountKey IS NOT NULL THEN 1 ELSE 0 END;
END
GO

/* ============================================================================
   6b. fact_account_progress  (both sources) -- creates the Stage 1
   ("Discovered") tracking row for any account that doesn't have one yet.

   Never touches an existing progress row -- an account already being
   tracked keeps whatever stage/status/owner/etc. a person has since set,
   even if this proc runs again. This only handles brand-new accounts.

   AccountTypeKey and SORKey are pre-filled from platform_account_type_map
   as a suggested default based on the account's Platform, saving manual
   entry for the common case -- but both remain ordinary editable columns
   on fact_account_progress, so an analyst can override either one for an
   individual account that doesn't fit its Platform's usual pattern.
   Accounts on a Platform that hasn't been mapped yet in
   platform_account_type_map simply get NULL for both and are picked up
   once that mapping is completed (see vw_review_platform_sor_accounttype
   below to find unmapped platforms).
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_FactAccountProgress
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @DiscoveredStageKey INT = (SELECT StageKey FROM dim_blueprint_stage WHERE StageName = 'Discovered');
    DECLARE @NotStartedStatusKey INT = (SELECT StatusKey FROM dim_progress_status WHERE StatusName = 'Not Started');

    INSERT INTO fact_account_progress (AccountKey, CurrentStageKey, CurrentStatusKey, AccountTypeKey, SORKey)
    SELECT fa.AccountKey, @DiscoveredStageKey, @NotStartedStatusKey, pm.AccountTypeKey, pm.SORKey
    FROM fact_account fa
    LEFT JOIN platform_account_type_map pm ON pm.PlatformKey = fa.PlatformKey
    WHERE fa.IsDeleted = 0
      AND NOT EXISTS (SELECT 1 FROM fact_account_progress fap WHERE fap.AccountKey = fa.AccountKey);
END
GO


CREATE OR ALTER PROCEDURE usp_Load_AccountProgressAutoAdvance
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @DiscoveredStageKey INT = (SELECT StageKey FROM dim_blueprint_stage WHERE StageName = 'Discovered');
    DECLARE @OnboardedStageKey INT = (SELECT StageKey FROM dim_blueprint_stage WHERE StageName = 'Onboarded to Vault');
    DECLARE @NotStartedStatusKey INT = (SELECT StatusKey FROM dim_progress_status WHERE StatusName = 'Not Started');
    -- ISNULL guard: if this row were ever somehow missing, @DiscoverySourceSystemKey
    -- would be NULL, and "fa.SourceSystemKey <> NULL" is NULL (never true) for
    -- every row -- silently disabling auto-advance for every account, a far
    -- worse regression than the one this script fixes. Falling back to -1
    -- (never a real SourceSystemKey) instead makes a missing row a no-op for
    -- this new condition, not a silent full outage.
    DECLARE @DiscoverySourceSystemKey INT = ISNULL((SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'DISCOVERY'), -1);

    UPDATE fap
    SET fap.CurrentStageKey = @OnboardedStageKey,
        fap.LastUpdated = SYSUTCDATETIME()
    FROM fact_account_progress fap
    JOIN fact_account fa ON fa.AccountKey = fap.AccountKey
    LEFT JOIN dim_safe ds ON ds.SafeKey = fa.SafeKey
    WHERE fap.CurrentStageKey = @DiscoveredStageKey
      AND fap.CurrentStatusKey = @NotStartedStatusKey
      AND fa.IsDeleted = 0
      AND fa.SourceSystemKey <> @DiscoverySourceSystemKey
      AND (ds.SafeKey IS NULL OR ds.SafeName NOT LIKE '%[_]Pending%');
END
GO

/* ============================================================================
   7. fact_safe_entitlement + bridge_entitlement_permission  (both sources)

   Uses CROSS APPLY (VALUES ...) to unpivot each source's wide boolean
   columns into the long/normalized bridge table, mapping raw column names
   to canonical permissions via permission_alias.

   NOTE ON APPROACH: earlier revisions of this proc tried to capture each
   newly-inserted EntitlementKey via OUTPUT ... INTO a table variable
   alongside staging columns like SafeUrlId/MemberId. That doesn't work --
   OUTPUT on an INSERT can only reference inserted./deleted. columns (the
   target table's own columns), never columns from the source SELECT, so
   SafeUrlId/MemberId/CAOSafeID/CAOOwnerID (which aren't columns on
   fact_safe_entitlement at all) can never appear there. Instead, each
   INSERT below is followed by a second statement that re-joins the same
   staging rows back to fact_safe_entitlement on the natural key
   (SafeKey, MemberType, UserKey, GroupKey, SnapshotDate) to find the
   EntitlementKey each row landed at. This assumes that natural key is
   unique per snapshot, which holds as long as the staging export itself
   has no duplicate (Safe, Member) rows -- true given the DESIGN
   ASSUMPTION at the top of this file that staging holds one clean current
   snapshot; a staging table with duplicate rows would fan out here.
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_FactSafeEntitlement
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');
    DECLARE @Today DATE = CAST(SYSUTCDATETIME() AS DATE);

    -- clear and reload each run -- entitlement exports are point-in-time
    -- snapshots, so this table is treated as "current state" rather than
    -- something to incrementally MERGE row-by-row like the dimensions above
    DELETE bep FROM bridge_entitlement_permission bep
        JOIN fact_safe_entitlement fse ON fse.EntitlementKey = bep.EntitlementKey
        JOIN dim_safe sf ON sf.SafeKey = fse.SafeKey
        WHERE sf.SourceSystemKey IN (@PrivCloudKey, @SelfHostedKey);
    DELETE fse FROM fact_safe_entitlement fse
        JOIN dim_safe sf ON sf.SafeKey = fse.SafeKey
        WHERE sf.SourceSystemKey IN (@PrivCloudKey, @SelfHostedKey);

    -- ---- Privilege Cloud entitlements: resolved (matches dim_user/dim_group) ----
    INSERT INTO fact_safe_entitlement (SafeKey, MemberType, UserKey, GroupKey, MembershipExpirationDate,
                                        IsExpiredMembershipEnable, IsPredefinedUser, SnapshotDate)
    SELECT sf.SafeKey, e.MemberType, u.UserKey, g.GroupKey,
           e.MembershipExpirationDate, e.IsExpiredMembershipEnable, e.IsPredefinedUser, @Today
    FROM stg_pc_entitlements e
    JOIN dim_safe sf ON sf.SourceSystemKey = @PrivCloudKey AND sf.SafeUrlId = e.SafeUrlId
    LEFT JOIN dim_user  u ON e.MemberType = 'User'  AND u.SourceSystemKey = @PrivCloudKey AND u.SourceUserId  = e.MemberId
    LEFT JOIN dim_group g ON e.MemberType = 'Group' AND g.SourceSystemKey = @PrivCloudKey AND g.SourceGroupId = e.MemberId
    WHERE (e.MemberType = 'User'  AND u.UserKey  IS NOT NULL)
       OR (e.MemberType = 'Group' AND g.GroupKey IS NOT NULL);

    INSERT INTO bridge_entitlement_permission (EntitlementKey, PermissionKey, IsGranted)
    SELECT fse.EntitlementKey, pa.PermissionKey, v.IsGranted
    FROM stg_pc_entitlements e
    JOIN dim_safe sf ON sf.SourceSystemKey = @PrivCloudKey AND sf.SafeUrlId = e.SafeUrlId
    LEFT JOIN dim_user  u ON e.MemberType = 'User'  AND u.SourceSystemKey = @PrivCloudKey AND u.SourceUserId  = e.MemberId
    LEFT JOIN dim_group g ON e.MemberType = 'Group' AND g.SourceSystemKey = @PrivCloudKey AND g.SourceGroupId = e.MemberId
    JOIN fact_safe_entitlement fse
        ON fse.SafeKey = sf.SafeKey
       AND fse.MemberType = e.MemberType
       AND ISNULL(fse.UserKey, -1)  = ISNULL(u.UserKey, -1)
       AND ISNULL(fse.GroupKey, -1) = ISNULL(g.GroupKey, -1)
       AND fse.SnapshotDate = @Today
    CROSS APPLY (VALUES
        ('UseAccounts', e.UseAccounts), ('RetrieveAccounts', e.RetrieveAccounts), ('ListAccounts', e.ListAccounts),
        ('AddAccounts', e.AddAccounts), ('UpdateAccountContent', e.UpdateAccountContent),
        ('UpdateAccountProperties', e.UpdateAccountProperties),
        ('InitiateCPMAccountManagementOperations', e.InitiateCPMAccountManagementOperations),
        ('SpecifyNextAccountContent', e.SpecifyNextAccountContent), ('RenameAccounts', e.RenameAccounts),
        ('DeleteAccounts', e.DeleteAccounts), ('UnlockAccounts', e.UnlockAccounts), ('ManageSafe', e.ManageSafe),
        ('ManageSafeMembers', e.ManageSafeMembers), ('BackupSafe', e.BackupSafe), ('ViewAuditLog', e.ViewAuditLog),
        ('ViewSafeMembers', e.ViewSafeMembers), ('AccessWithoutConfirmation', e.AccessWithoutConfirmation),
        ('CreateFolders', e.CreateFolders), ('DeleteFolders', e.DeleteFolders),
        ('MoveAccountsAndFolders', e.MoveAccountsAndFolders),
        ('RequestsAuthorizationLevel1', e.RequestsAuthorizationLevel1),
        ('RequestsAuthorizationLevel2', e.RequestsAuthorizationLevel2)
    ) AS v(RawPermissionName, IsGranted)
    JOIN permission_alias pa ON pa.SourceSystemKey = @PrivCloudKey AND pa.RawPermissionName = v.RawPermissionName
    WHERE v.IsGranted IS NOT NULL
      AND ((e.MemberType = 'User'  AND u.UserKey  IS NOT NULL)
        OR (e.MemberType = 'Group' AND g.GroupKey IS NOT NULL));

    -- ---- Privilege Cloud entitlements: unresolved (CyberArk Identity/
    -- Entra-federated user or built-in cloud role -- see UnresolvedMemberId's
    -- own comment in 01_BlueTrack_CoreSchema.sql). Preserved rather than
    -- dropped. The bridge rejoin below keys on UnresolvedMemberId, not
    -- UserKey/GroupKey (both always NULL here) -- more than one unresolved
    -- member of the same MemberType can exist on the same safe, so
    -- UserKey/GroupKey alone would not be a unique rejoin key the way it
    -- is for the resolved case above.
    INSERT INTO fact_safe_entitlement (SafeKey, MemberType, UnresolvedMemberId, MembershipExpirationDate,
                                        IsExpiredMembershipEnable, IsPredefinedUser, SnapshotDate)
    SELECT sf.SafeKey, e.MemberType, e.MemberId,
           e.MembershipExpirationDate, e.IsExpiredMembershipEnable, e.IsPredefinedUser, @Today
    FROM stg_pc_entitlements e
    JOIN dim_safe sf ON sf.SourceSystemKey = @PrivCloudKey AND sf.SafeUrlId = e.SafeUrlId
    LEFT JOIN dim_user  u ON e.MemberType = 'User'  AND u.SourceSystemKey = @PrivCloudKey AND u.SourceUserId  = e.MemberId
    LEFT JOIN dim_group g ON e.MemberType = 'Group' AND g.SourceSystemKey = @PrivCloudKey AND g.SourceGroupId = e.MemberId
    WHERE (e.MemberType = 'User'  AND u.UserKey  IS NULL)
       OR (e.MemberType = 'Group' AND g.GroupKey IS NULL);

    INSERT INTO bridge_entitlement_permission (EntitlementKey, PermissionKey, IsGranted)
    SELECT fse.EntitlementKey, pa.PermissionKey, v.IsGranted
    FROM stg_pc_entitlements e
    JOIN dim_safe sf ON sf.SourceSystemKey = @PrivCloudKey AND sf.SafeUrlId = e.SafeUrlId
    LEFT JOIN dim_user  u ON e.MemberType = 'User'  AND u.SourceSystemKey = @PrivCloudKey AND u.SourceUserId  = e.MemberId
    LEFT JOIN dim_group g ON e.MemberType = 'Group' AND g.SourceSystemKey = @PrivCloudKey AND g.SourceGroupId = e.MemberId
    JOIN fact_safe_entitlement fse
        ON fse.SafeKey = sf.SafeKey
       AND fse.MemberType = e.MemberType
       AND fse.UnresolvedMemberId = e.MemberId
       AND fse.SnapshotDate = @Today
    CROSS APPLY (VALUES
        ('UseAccounts', e.UseAccounts), ('RetrieveAccounts', e.RetrieveAccounts), ('ListAccounts', e.ListAccounts),
        ('AddAccounts', e.AddAccounts), ('UpdateAccountContent', e.UpdateAccountContent),
        ('UpdateAccountProperties', e.UpdateAccountProperties),
        ('InitiateCPMAccountManagementOperations', e.InitiateCPMAccountManagementOperations),
        ('SpecifyNextAccountContent', e.SpecifyNextAccountContent), ('RenameAccounts', e.RenameAccounts),
        ('DeleteAccounts', e.DeleteAccounts), ('UnlockAccounts', e.UnlockAccounts), ('ManageSafe', e.ManageSafe),
        ('ManageSafeMembers', e.ManageSafeMembers), ('BackupSafe', e.BackupSafe), ('ViewAuditLog', e.ViewAuditLog),
        ('ViewSafeMembers', e.ViewSafeMembers), ('AccessWithoutConfirmation', e.AccessWithoutConfirmation),
        ('CreateFolders', e.CreateFolders), ('DeleteFolders', e.DeleteFolders),
        ('MoveAccountsAndFolders', e.MoveAccountsAndFolders),
        ('RequestsAuthorizationLevel1', e.RequestsAuthorizationLevel1),
        ('RequestsAuthorizationLevel2', e.RequestsAuthorizationLevel2)
    ) AS v(RawPermissionName, IsGranted)
    JOIN permission_alias pa ON pa.SourceSystemKey = @PrivCloudKey AND pa.RawPermissionName = v.RawPermissionName
    WHERE v.IsGranted IS NOT NULL
      AND ((e.MemberType = 'User'  AND u.UserKey  IS NULL)
        OR (e.MemberType = 'Group' AND g.GroupKey IS NULL));

    -- ---- Self-Hosted entitlements (CAOwners) ----
    -- CAOOwnerType decodes via dim_selfhosted_code type 10: 0=User, 1=Group, 2=Gateway account.
    -- Gateway-account owners aren't represented in dim_user or dim_group -- they're
    -- excluded below via the WHERE clause (rather than relying on the CHECK
    -- constraint to reject them). Revisit this if Gateway account owners
    -- matter for your reporting.
    INSERT INTO fact_safe_entitlement (SafeKey, MemberType, UserKey, GroupKey, MembershipExpirationDate,
                                        IsExpiredMembershipEnable, IsPredefinedUser, SnapshotDate)
    SELECT sf.SafeKey,
           CASE o.CAOOwnerType WHEN 0 THEN 'User' WHEN 1 THEN 'Group' ELSE NULL END,
           u.UserKey, g.GroupKey, o.CAOExpirationDate, NULL, NULL, @Today
    FROM stg_sh_owners o
    JOIN dim_safe sf ON sf.SourceSystemKey = @SelfHostedKey AND sf.SafeUrlId = CAST(o.CAOSafeID AS NVARCHAR(300))
    LEFT JOIN dim_user  u ON o.CAOOwnerType = 0 AND u.SourceSystemKey = @SelfHostedKey AND u.SourceUserId  = CAST(o.CAOOwnerID AS NVARCHAR(100))
    LEFT JOIN dim_group g ON o.CAOOwnerType = 1 AND g.SourceSystemKey = @SelfHostedKey AND g.SourceGroupId = CAST(o.CAOOwnerID AS NVARCHAR(100))
    WHERE o.CAOOwnerType IN (0, 1);

    INSERT INTO bridge_entitlement_permission (EntitlementKey, PermissionKey, IsGranted)
    SELECT fse.EntitlementKey, pa.PermissionKey, dbo.ufn_YNToBit(v.RawValue)
    FROM stg_sh_owners o
    JOIN dim_safe sf ON sf.SourceSystemKey = @SelfHostedKey AND sf.SafeUrlId = CAST(o.CAOSafeID AS NVARCHAR(300))
    LEFT JOIN dim_user  u ON o.CAOOwnerType = 0 AND u.SourceSystemKey = @SelfHostedKey AND u.SourceUserId  = CAST(o.CAOOwnerID AS NVARCHAR(100))
    LEFT JOIN dim_group g ON o.CAOOwnerType = 1 AND g.SourceSystemKey = @SelfHostedKey AND g.SourceGroupId = CAST(o.CAOOwnerID AS NVARCHAR(100))
    JOIN fact_safe_entitlement fse
        ON fse.SafeKey = sf.SafeKey
       AND fse.MemberType = CASE o.CAOOwnerType WHEN 0 THEN 'User' WHEN 1 THEN 'Group' ELSE NULL END
       AND ISNULL(fse.UserKey, -1)  = ISNULL(u.UserKey, -1)
       AND ISNULL(fse.GroupKey, -1) = ISNULL(g.GroupKey, -1)
       AND fse.SnapshotDate = @Today
    CROSS APPLY (VALUES
        ('CAOList', o.CAOList), ('CAORetrieve', o.CAORetrieve), ('CAOCreateObject', o.CAOCreateObject),
        ('CAOUpdateObject', o.CAOUpdateObject), ('CAOUpdateObjectProperties', o.CAOUpdateObjectProperties),
        ('CAORenameObject', o.CAORenameObject), ('CAODelete', o.CAODelete),
        ('CAOInitiateCPMChange', o.CAOInitiateCPMChange),
        ('CAOInitiateCPMChangeWithManualPassword', o.CAOInitiateCPMChangeWithManualPassword),
        ('CAOCreateFolder', o.CAOCreateFolder), ('CAODeleteFolder', o.CAODeleteFolder),
        ('CAOUnlockObject', o.CAOUnlockObject), ('CAOMoveFrom', o.CAOMoveFrom), ('CAOMoveInto', o.CAOMoveInto),
        ('CAOManageSafe', o.CAOManageSafe), ('CAOManageSafeOwners', o.CAOManageSafeOwners),
        ('CAOBackup', o.CAOBackup), ('CAONoConfirmRequired', o.CAONoConfirmRequired),
        ('CAOEventsList', o.CAOEventsList)
    ) AS v(RawPermissionName, RawValue)
    JOIN permission_alias pa ON pa.SourceSystemKey = @SelfHostedKey AND pa.RawPermissionName = v.RawPermissionName
    WHERE o.CAOOwnerType IN (0, 1) AND dbo.ufn_YNToBit(v.RawValue) IS NOT NULL;
END
GO


/* ============================================================================
   REPORTING VIEW -- effective safe access, direct + group-expanded
   One row per (Safe, User) pair who can access it, whether granted
   directly or through a Group entitlement expanded via
   bridge_group_membership. A user with both direct and group-based access
   to the same safe intentionally appears twice (once per AccessPath) --
   that's informative, not a duplicate to dedupe away. This is the natural
   source for "how many actual known CyberArk users touch this safe/
   application" questions, e.g. for license-count estimation.
   ============================================================================ */
CREATE OR ALTER VIEW vw_effective_safe_access AS
SELECT fse.SafeKey, u.UserKey, 'Direct' AS AccessPath, fse.EntitlementKey AS SourceEntitlementKey
FROM fact_safe_entitlement fse
JOIN dim_user u ON u.UserKey = fse.UserKey
WHERE fse.MemberType = 'User'
UNION ALL
SELECT fse.SafeKey, bgm.UserKey, 'Via Group: ' + g.GroupName, fse.EntitlementKey
FROM fact_safe_entitlement fse
JOIN dim_group g ON g.GroupKey = fse.GroupKey
JOIN bridge_group_membership bgm ON bgm.GroupKey = g.GroupKey
WHERE fse.MemberType = 'Group';
GO

/* ============================================================================
   REPORTING VIEW -- CSV export source
   Point your CSV export (SSMS "Results to File", bcp, or an app-level
   export button) at this view rather than the raw fact table.
   ============================================================================ */
CREATE OR ALTER VIEW vw_export_account_progress AS
SELECT
    ss.SourceSystemName,
    fa.SourceAccountId,
    fa.AccountName,
    fa.UserName,
    fa.Address,
    dp.PlatformName,
    ds.SafeName,
    at.AccountTypeName,
    sor.SORName               AS SourceOfRecord,
    stg.StageName            AS CurrentStage,
    stat.StatusName          AS CurrentStatus,
    rl.RiskLevelName          AS RiskLevel,
    fap.OwnerName,
    fap.BusinessUnit,
    fap.TargetRemediationDate,
    fap.ActualCompletionDate,
    fap.LastUpdated,
    fap.Notes
FROM fact_account_progress fap
JOIN fact_account fa        ON fa.AccountKey = fap.AccountKey
JOIN dim_source_system ss   ON ss.SourceSystemKey = fa.SourceSystemKey
LEFT JOIN dim_platform dp   ON dp.PlatformKey = fa.PlatformKey
LEFT JOIN dim_safe ds       ON ds.SafeKey = fa.SafeKey
LEFT JOIN dim_account_type at ON at.AccountTypeKey = fap.AccountTypeKey
LEFT JOIN dim_source_of_record sor ON sor.SORKey = fap.SORKey
LEFT JOIN dim_risk_level rl ON rl.RiskLevelKey = fap.RiskLevelKey
JOIN dim_blueprint_stage stg ON stg.StageKey = fap.CurrentStageKey
JOIN dim_progress_status stat ON stat.StatusKey = fap.CurrentStatusKey;
GO

/* ============================================================================
   REPORTING VIEW -- platform mapping review queue
   Surfaces every Platform in use, whether it's been mapped in
   platform_account_type_map yet, and a sample Address from an account on
   that Platform as a manual sanity-check hint. Address is deliberately
   NOT used anywhere in the automated ETL logic -- it's too unreliable as a
   primary signal (a hostname doesn't reliably tell you what controls the
   identity logging into it) -- but it's a useful secondary confirmation
   for a human reviewer curating platform_account_type_map (e.g. an FQDN
   with a domain suffix supporting an 'Active Directory' classification).
   Point whoever maintains platform_account_type_map at this view; it does
   not write to any table.
   ============================================================================ */
CREATE OR ALTER VIEW vw_review_platform_sor_accounttype AS
SELECT
    dp.PlatformKey,
    ss.SourceSystemName,
    dp.PlatformID,
    dp.PlatformName,
    pm.AccountTypeKey,
    at.AccountTypeName,
    pm.SORKey,
    sor.SORName                AS SourceOfRecord,
    CASE WHEN pm.PlatformKey IS NULL THEN 1 ELSE 0 END AS IsUnmapped,
    accountCounts.AccountCount,
    sampleAccount.Address      AS SampleAddress,
    sampleAccount.AccountName  AS SampleAccountName
FROM dim_platform dp
JOIN dim_source_system ss ON ss.SourceSystemKey = dp.SourceSystemKey
LEFT JOIN platform_account_type_map pm ON pm.PlatformKey = dp.PlatformKey
LEFT JOIN dim_account_type at ON at.AccountTypeKey = pm.AccountTypeKey
LEFT JOIN dim_source_of_record sor ON sor.SORKey = pm.SORKey
OUTER APPLY (
    SELECT COUNT(*) AS AccountCount
    FROM fact_account fa
    WHERE fa.PlatformKey = dp.PlatformKey AND fa.IsDeleted = 0
) accountCounts
OUTER APPLY (
    SELECT TOP 1 fa.Address, fa.AccountName
    FROM fact_account fa
    WHERE fa.PlatformKey = dp.PlatformKey AND fa.IsDeleted = 0 AND fa.Address IS NOT NULL
    ORDER BY fa.AccountKey
) sampleAccount;
GO


/* ============================================================================
   Matching procedure. Proposes candidate matches only -- inserts new rows,
   never updates or deletes an existing reviewer's decision (IsConfirmed,
   ReviewedBy, RejectedFlag are left untouched on rows that already exist).
   Called as part of usp_RunFullLoad (defined in file 04), after
   usp_Load_FactAccount.
   ============================================================================ */
CREATE OR ALTER PROCEDURE usp_Load_AccountReconciliation
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');

    /* ---------------------------------------------------------------------
       METHOD 1 -- exact SourceAccountId (SafeID_FileID) match.
       See the critical assumption at the top of this file. Confidence is
       marked 'High' on the assumption that this environment did a
       lift-and-shift migration -- downgrade to 'Needs Review' in the
       UPDATE below if you confirm accounts were re-onboarded instead of
       migrated in place.
    --------------------------------------------------------------------- */
    INSERT INTO account_reconciliation (LegacyAccountKey, CurrentAccountKey, MatchMethod, MatchConfidence, Notes)
    SELECT sh.AccountKey, pc.AccountKey, 'SafeFileID_ExactMatch', 'High',
           'Matched on identical SourceAccountId (SafeID_FileID) across sources -- confirm this environment used an in-place vault migration before relying on this match.'
    FROM fact_account sh
    JOIN fact_account pc
        ON pc.SourceSystemKey = @PrivCloudKey
       AND pc.SourceAccountId = sh.SourceAccountId
       AND pc.IsDeleted = 0
    WHERE sh.SourceSystemKey = @SelfHostedKey
      AND sh.IsDeleted = 0
      AND NOT EXISTS (
          SELECT 1 FROM account_reconciliation ar
          WHERE ar.LegacyAccountKey = sh.AccountKey AND ar.CurrentAccountKey = pc.AccountKey
      );

    /* ---------------------------------------------------------------------
       METHOD 2 -- attribute-based match for Self-Hosted accounts that had
       no exact ID match above. Matches on Safe name + username + address,
       which is a reasonable fallback signal but not proof of identity --
       e.g. a decommissioned account and its replacement could share these
       same attribute values. Always leaves MatchConfidence at a level that
       forces human review; never auto-confirmed.

       If more than one Privilege Cloud candidate matches the same
       Self-Hosted account (or vice versa), ALL candidates are inserted
       with confidence 'Needs Review' rather than picking one arbitrarily --
       an ambiguous match is a worse error to hide than to surface.
    --------------------------------------------------------------------- */
    ;WITH Candidates AS (
        SELECT
            sh.AccountKey AS LegacyAccountKey,
            pc.AccountKey AS CurrentAccountKey,
            COUNT(*) OVER (PARTITION BY sh.AccountKey) AS MatchesForLegacy,
            COUNT(*) OVER (PARTITION BY pc.AccountKey) AS MatchesForCurrent
        FROM fact_account sh
        JOIN dim_safe shsafe ON shsafe.SafeKey = sh.SafeKey
        JOIN fact_account pc
            ON pc.SourceSystemKey = @PrivCloudKey
           AND pc.IsDeleted = 0
           AND pc.UserName = sh.UserName
           AND pc.Address  = sh.Address
        JOIN dim_safe pcsafe ON pcsafe.SafeKey = pc.SafeKey AND pcsafe.SafeName = shsafe.SafeName
        WHERE sh.SourceSystemKey = @SelfHostedKey
          AND sh.IsDeleted = 0
          AND sh.UserName IS NOT NULL AND sh.Address IS NOT NULL
          AND NOT EXISTS (SELECT 1 FROM account_reconciliation ar WHERE ar.LegacyAccountKey = sh.AccountKey)  -- skip accounts already matched by Method 1
    )
    INSERT INTO account_reconciliation (LegacyAccountKey, CurrentAccountKey, MatchMethod, MatchConfidence, Notes)
    SELECT LegacyAccountKey, CurrentAccountKey, 'Attribute_Match',
           CASE WHEN MatchesForLegacy = 1 AND MatchesForCurrent = 1 THEN 'Medium' ELSE 'Needs Review' END,
           CASE WHEN MatchesForLegacy > 1 OR MatchesForCurrent > 1
                THEN 'Ambiguous: matched on Safe name + username + address, but multiple candidates exist on one or both sides -- resolve manually.'
                ELSE 'Matched on Safe name + username + address (no exact ID match found). Confirm manually before treating as the same account.'
           END
    FROM Candidates c
    WHERE NOT EXISTS (
        SELECT 1 FROM account_reconciliation ar
        WHERE ar.LegacyAccountKey = c.LegacyAccountKey AND ar.CurrentAccountKey = c.CurrentAccountKey
    );
END
GO



/* ============================================================================
   Reporting view: migration status per real-world account, for Power BI.
   Three buckets: Self-Hosted only (not yet migrated / candidate for
   decommission), Migrated (confirmed match exists in both), and Privilege
   Cloud only (net-new cloud account, never existed in Self-Hosted).

   Deliberately only counts a match as "Migrated" once a human has set
   IsConfirmed = 1 and RejectedFlag = 0 -- an unreviewed proposed match does
   not count as confirmed migration for reporting purposes.
   ============================================================================ */
CREATE OR ALTER VIEW vw_account_migration_status AS
SELECT
    fa.AccountKey,
    fa.SourceAccountId,
    fa.AccountName,
    fa.UserName,
    fa.Address,
    ds.SafeName,
    CASE
        WHEN fa.SourceSystemKey = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED')
             AND EXISTS (SELECT 1 FROM account_reconciliation ar WHERE ar.LegacyAccountKey = fa.AccountKey AND ar.IsConfirmed = 1 AND ar.RejectedFlag = 0)
            THEN 'Migrated to Privilege Cloud'
        WHEN fa.SourceSystemKey = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED')
            THEN 'Self-Hosted Only (not yet migrated / unconfirmed)'
        WHEN fa.SourceSystemKey = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD')
             AND EXISTS (SELECT 1 FROM account_reconciliation ar WHERE ar.CurrentAccountKey = fa.AccountKey AND ar.IsConfirmed = 1 AND ar.RejectedFlag = 0)
            THEN 'Migrated (Cloud side of a confirmed match)'
        WHEN fa.SourceSystemKey = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD')
            THEN 'Privilege Cloud Only (net-new)'
        ELSE 'Other Source'
    END AS MigrationStatus,
    fa.IsDeleted
FROM fact_account fa
JOIN dim_safe ds ON ds.SafeKey = fa.SafeKey;
GO



/* ============================================================================
   Reviewer helper: a small queue view of everything still awaiting a human
   decision. Exposes a ReviewPriority column (ambiguous/low-confidence
   first) rather than sorting inside the view itself -- SQL Server doesn't
   allow ORDER BY in a view definition (it's rejected outright, and the
   common TOP 100 PERCENT workaround doesn't reliably preserve order on a
   later SELECT from the view either, so it isn't a real fix). Order by
   ReviewPriority, MatchedDate when you query this view:
       SELECT * FROM vw_reconciliation_review_queue
       ORDER BY ReviewPriority, MatchedDate;
   Point a simple review screen (or just SSMS) at this.
   ============================================================================ */
CREATE OR ALTER VIEW vw_reconciliation_review_queue AS
SELECT
    ar.ReconciliationKey,
    legacy.SourceAccountId AS SelfHostedAccountId, legacy.AccountName AS SelfHostedAccountName,
    legacy.UserName AS SelfHostedUserName, legacy.Address AS SelfHostedAddress,
    current_.SourceAccountId AS PrivCloudAccountId, current_.AccountName AS PrivCloudAccountName,
    current_.UserName AS PrivCloudUserName, current_.Address AS PrivCloudAddress,
    ar.MatchMethod, ar.MatchConfidence, ar.MatchedDate, ar.Notes,
    CASE ar.MatchConfidence WHEN 'Needs Review' THEN 1 WHEN 'Medium' THEN 2 WHEN 'High' THEN 3 END AS ReviewPriority
FROM account_reconciliation ar
JOIN fact_account legacy   ON legacy.AccountKey = ar.LegacyAccountKey
JOIN fact_account current_ ON current_.AccountKey = ar.CurrentAccountKey
WHERE ar.IsConfirmed = 0 AND ar.RejectedFlag = 0;
GO


/* ----------------------------------------------------------------------------
   1. dim_date population
   Adjust @StartDate/@EndDate to your engagement's actual timeline -- this
   defaults to a broad range so it doesn't need re-running as the project
   goes on. Safe to run once; re-running only adds nothing (INSERT guarded
   by NOT EXISTS).
---------------------------------------------------------------------------- */
DECLARE @StartDate DATE = '2026-01-01';
DECLARE @EndDate   DATE = '2028-12-31';

;WITH DateSeries AS (
    SELECT @StartDate AS FullDate
    UNION ALL
    SELECT DATEADD(DAY, 1, FullDate) FROM DateSeries WHERE FullDate < @EndDate
)
INSERT INTO dim_date (DateKey, FullDate, Year, Quarter, Month, MonthName, Week, DayOfMonth, DayName)
SELECT
    CAST(FORMAT(FullDate, 'yyyyMMdd') AS INT),
    FullDate,
    YEAR(FullDate),
    DATEPART(QUARTER, FullDate),
    MONTH(FullDate),
    DATENAME(MONTH, FullDate),
    DATEPART(WEEK, FullDate),
    DAY(FullDate),
    DATENAME(WEEKDAY, FullDate)
FROM DateSeries
WHERE CAST(FORMAT(FullDate, 'yyyyMMdd') AS INT) NOT IN (SELECT DateKey FROM dim_date)
OPTION (MAXRECURSION 0);
GO



/* ----------------------------------------------------------------------------
   2. vw_powerbi_accounts
   One row per account (current state). Deliberately keeps foreign keys
   (PlatformKey, SafeKey, CurrentStageKey, etc.) rather than resolving them
   to names here -- resolving names in the view would bypass Power BI's own
   relationship/filter engine and break slicer interactions. Import this as
   one table and build relationships to the dimension tables in Power BI's
   Model view.

   Accounts with no fact_account_progress row yet (LEFT JOIN) show as
   NULL stage/status -- decide in Power BI whether to treat that as
   "Not Started" via a calculated column, or surface it as a genuine
   "not yet tracked" data-quality signal. I'd lean toward the latter: an
   account that exists in the vault but has no progress row is worth
   knowing about, not silently defaulting.
---------------------------------------------------------------------------- */
CREATE OR ALTER VIEW vw_powerbi_accounts AS
SELECT
    fa.AccountKey,
    fa.SourceSystemKey,
    fa.SourceAccountId,
    fa.AccountName,
    fa.Address,
    fa.UserName,
    fa.PlatformKey,
    fa.SafeKey,
    fa.SecretType,
    fa.AutoManaged,
    fa.CPMStatus,
    fa.LastCPMModifiedDate,
    fa.LastReconciledDate,
    fa.LastVerifiedDate,
    fa.IsDeleted,
    fa.CreatedDate,
    fap.ProgressKey,
    fap.CurrentStageKey,
    fap.CurrentStatusKey,
    fap.AccountTypeKey,
    fap.SORKey,
    fap.RiskLevelKey,
    fap.OwnerName,
    fap.BusinessUnit,
    fap.TargetRemediationDate,
    fap.ActualCompletionDate,
    fap.LastUpdated AS ProgressLastUpdated,
    -- surfaces a plain flag for a common Power BI card/KPI without needing a DAX measure
    CASE WHEN fap.ProgressKey IS NULL THEN 1 ELSE 0 END AS IsUntrackedInBlueprint,
    -- surfaces overdue remediations directly for a simple visual filter
    CASE WHEN fap.TargetRemediationDate < CAST(GETDATE() AS DATE)
              AND fap.ActualCompletionDate IS NULL
         THEN 1 ELSE 0 END AS IsOverdue
FROM fact_account fa
LEFT JOIN fact_account_progress fap ON fap.AccountKey = fa.AccountKey;
GO



/* ----------------------------------------------------------------------------
   3. vw_powerbi_entitlements
   Grain: one row per (safe, member, permission). Keeps FKs for the same
   reason as above. This is the table to relate to dim_safe, dim_user,
   dim_group, and dim_permission for access-review visuals ("who can
   retrieve passwords from which safes", entitlement counts by safe, etc.)
---------------------------------------------------------------------------- */
CREATE OR ALTER VIEW vw_powerbi_entitlements AS
SELECT
    bep.EntitlementKey,
    fse.SafeKey,
    fse.MemberType,
    fse.UserKey,
    fse.GroupKey,
    fse.SnapshotDate,
    bep.PermissionKey,
    bep.IsGranted
FROM fact_safe_entitlement fse
JOIN bridge_entitlement_permission bep ON bep.EntitlementKey = fse.EntitlementKey;
GO



/* ----------------------------------------------------------------------------
   4. usp_Load_FactAccountProgressHistory
   Run this on a schedule (SQL Agent job, nightly or weekly -- match your
   Blueprint check-in cadence) to append one snapshot row per account per
   run. This is what makes trend-over-time visuals possible in Power BI;
   fact_account_progress alone only ever shows current state.
---------------------------------------------------------------------------- */
CREATE OR ALTER PROCEDURE usp_Load_FactAccountProgressHistory
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @TodayKey INT = CAST(FORMAT(GETDATE(), 'yyyyMMdd') AS INT);

    IF NOT EXISTS (SELECT 1 FROM dim_date WHERE DateKey = @TodayKey)
    BEGIN
        RAISERROR('dim_date has no row for today -- extend the date range and re-run the dim_date population script before scheduling this proc.', 16, 1);
        RETURN;
    END

    -- avoid duplicate snapshots if this is run more than once on the same day
    DELETE FROM fact_account_progress_history WHERE SnapshotDateKey = @TodayKey;

    INSERT INTO fact_account_progress_history (SnapshotDateKey, AccountKey, StageKey, StatusKey, RiskLevelKey)
    SELECT @TodayKey, fap.AccountKey, fap.CurrentStageKey, fap.CurrentStatusKey, fap.RiskLevelKey
    FROM fact_account_progress fap
    JOIN fact_account fa ON fa.AccountKey = fap.AccountKey
    WHERE fa.IsDeleted = 0;
END
GO


CREATE OR ALTER VIEW vw_unresolved_entitlement_members AS
SELECT
    fse.EntitlementKey,
    fse.SafeKey,
    ds.SafeName,
    fse.MemberType,
    fse.UnresolvedMemberId,
    fse.MembershipExpirationDate,
    fse.SnapshotDate
FROM dbo.fact_safe_entitlement fse
JOIN dbo.dim_safe ds ON ds.SafeKey = fse.SafeKey
WHERE fse.UnresolvedMemberId IS NOT NULL;
GO

PRINT '02_BlueTrack_Baseline_EtlLoads.sql complete.';
GO
