/* ============================================================================
   48_BlueTrack_DecommissionPatterns.sql

   RUN THIS AFTER 01-47. Guarded / CREATE OR ALTER -- safe to re-run.
   Re-run it after moving the database to SQL Server 2025 (compatibility
   level 170) to turn on the Regex pattern type.

   D-186: names that mark a safe or account as being decommissioned, and
   safes to leave out of the import altogether. CyberArk's retention policy
   keeps a safe for a while after it's emptied, and people moving accounts
   between safes rename the old one, so a naming convention is the signal.
     web.app_config   three patterns, each a Mode (Off / Prefix / Suffix /
                      Regex) and a Value, set on Global Application
                      Configuration: SafeDecom*, AccountDecom*, SafeIgnore*.
                      Prefix and Suffix ignore case; so does Regex.
     dbo.fn_MatchesNamePattern(name, mode, value)  the one place matching
                      happens. Regex uses REGEXP_LIKE, which only exists on
                      SQL Server 2025 at compatibility level 170, so the
                      function is created with or without it (dynamic SQL,
                      so the script still runs on 2019/2022); there a Regex
                      pattern never matches, and the settings page refuses it.
     dbo.fn_RegexSupported()  1 when the function was built with regex.
     web.vw_decom_safe     safes matching the safe pattern (not ignored).
     web.vw_decom_account  accounts in those safes, or whose own name matches
                      the account pattern, with OtherSafes: the other
                      (not-flagged) safes holding an active account with the
                      same username + address (exact, both required, as D-183).
     usp_Load_FactAccount  (47) redefined: accounts in an ignored safe are
                      not imported, and existing ones are flagged deleted.
   ============================================================================ */

USE $DatabaseName$;
GO

IF COL_LENGTH('web.app_config', 'SafeDecomMode') IS NULL
BEGIN
    ALTER TABLE web.app_config ADD
        SafeDecomMode     NVARCHAR(10)  NOT NULL CONSTRAINT DF_app_config_SafeDecomMode DEFAULT 'Off'
                          CONSTRAINT CK_app_config_SafeDecomMode CHECK (SafeDecomMode IN ('Off', 'Prefix', 'Suffix', 'Regex')),
        SafeDecomValue    NVARCHAR(200) NULL,
        AccountDecomMode  NVARCHAR(10)  NOT NULL CONSTRAINT DF_app_config_AccountDecomMode DEFAULT 'Off'
                          CONSTRAINT CK_app_config_AccountDecomMode CHECK (AccountDecomMode IN ('Off', 'Prefix', 'Suffix', 'Regex')),
        AccountDecomValue NVARCHAR(200) NULL,
        SafeIgnoreMode    NVARCHAR(10)  NOT NULL CONSTRAINT DF_app_config_SafeIgnoreMode DEFAULT 'Off'
                          CONSTRAINT CK_app_config_SafeIgnoreMode CHECK (SafeIgnoreMode IN ('Off', 'Prefix', 'Suffix', 'Regex')),
        SafeIgnoreValue   NVARCHAR(200) NULL;
END
GO

DECLARE @Regex BIT = CASE WHEN CAST(SERVERPROPERTY('ProductMajorVersion') AS INT) >= 17
                           AND (SELECT compatibility_level FROM sys.databases WHERE name = DB_NAME()) >= 170
                          THEN 1 ELSE 0 END;
DECLARE @RegexBranch NVARCHAR(400) = CASE WHEN @Regex = 1
    THEN N'IF @Mode = N''Regex'' RETURN CASE WHEN REGEXP_LIKE(@Name, @Value, ''i'') THEN 1 ELSE 0 END;'
    ELSE N'-- Regex needs SQL Server 2025 (compatibility level 170): never matches here.' END;

EXEC (N'CREATE OR ALTER FUNCTION dbo.fn_MatchesNamePattern (@Name NVARCHAR(500), @Mode NVARCHAR(10), @Value NVARCHAR(200))
RETURNS BIT
AS
BEGIN
    -- D-186: generated by 48_BlueTrack_DecommissionPatterns.sql. Case-insensitive.
    IF @Name IS NULL OR @Value IS NULL OR @Value = N'''' OR @Mode IS NULL OR @Mode = N''Off'' RETURN 0;
    DECLARE @Length INT = DATALENGTH(@Value) / 2;
    IF @Mode = N''Prefix'' RETURN CASE WHEN UPPER(LEFT(@Name, @Length)) = UPPER(@Value) THEN 1 ELSE 0 END;
    IF @Mode = N''Suffix'' RETURN CASE WHEN UPPER(RIGHT(@Name, @Length)) = UPPER(@Value) THEN 1 ELSE 0 END;
    ' + @RegexBranch + N'
    RETURN 0;
END');

DECLARE @SupportedSql NVARCHAR(200) = N'CREATE OR ALTER FUNCTION dbo.fn_RegexSupported () RETURNS BIT AS BEGIN RETURN '
    + CASE WHEN @Regex = 1 THEN N'1' ELSE N'0' END + N'; END';
EXEC (@SupportedSql);
GO

CREATE OR ALTER VIEW web.vw_decom_safe
AS
SELECT ds.SafeKey, ds.SafeName, ss.SourceSystemName, da.ApplicationName,
       (SELECT COUNT(*) FROM dbo.fact_account fa WHERE fa.SafeKey = ds.SafeKey AND fa.IsDeleted = 0) AS ActiveAccountCount,
       (SELECT COUNT(*) FROM dbo.fact_account fa WHERE fa.SafeKey = ds.SafeKey AND fa.IsDeleted = 1) AS DeletedAccountCount
FROM dbo.dim_safe ds
JOIN dbo.dim_source_system ss ON ss.SourceSystemKey = ds.SourceSystemKey
LEFT JOIN web.dim_application da ON da.ApplicationKey = ds.ApplicationKey
CROSS JOIN web.app_config ac
WHERE dbo.fn_MatchesNamePattern(ds.SafeName, ac.SafeDecomMode, ac.SafeDecomValue) = 1
  AND dbo.fn_MatchesNamePattern(ds.SafeName, ac.SafeIgnoreMode, ac.SafeIgnoreValue) = 0;
GO

CREATE OR ALTER VIEW web.vw_decom_account
AS
SELECT fa.AccountKey, fa.AccountName, fa.UserName, fa.Address, fa.IsDeleted,
       ds.SafeName, ss.SourceSystemName,
       CAST(dbo.fn_MatchesNamePattern(ds.SafeName, ac.SafeDecomMode, ac.SafeDecomValue) AS BIT) AS InFlaggedSafe,
       CAST(dbo.fn_MatchesNamePattern(fa.AccountName, ac.AccountDecomMode, ac.AccountDecomValue) AS BIT) AS NameFlagged,
       (SELECT STRING_AGG(o.SafeName, ', ') WITHIN GROUP (ORDER BY o.SafeName)
        FROM (SELECT DISTINCT ods.SafeName
              FROM dbo.fact_account other
              JOIN dbo.dim_safe ods ON ods.SafeKey = other.SafeKey
              WHERE other.AccountKey <> fa.AccountKey AND other.IsDeleted = 0
                AND fa.UserName IS NOT NULL AND fa.Address IS NOT NULL
                AND UPPER(LTRIM(RTRIM(other.UserName))) = UPPER(LTRIM(RTRIM(fa.UserName)))
                AND UPPER(LTRIM(RTRIM(other.Address))) = UPPER(LTRIM(RTRIM(fa.Address)))
                AND dbo.fn_MatchesNamePattern(ods.SafeName, ac.SafeDecomMode, ac.SafeDecomValue) = 0) o) AS OtherSafes
FROM dbo.fact_account fa
LEFT JOIN dbo.dim_safe ds ON ds.SafeKey = fa.SafeKey
JOIN dbo.dim_source_system ss ON ss.SourceSystemKey = fa.SourceSystemKey
CROSS JOIN web.app_config ac
WHERE (dbo.fn_MatchesNamePattern(ds.SafeName, ac.SafeDecomMode, ac.SafeDecomValue) = 1
       AND dbo.fn_MatchesNamePattern(ds.SafeName, ac.SafeIgnoreMode, ac.SafeIgnoreValue) = 0)
   OR dbo.fn_MatchesNamePattern(fa.AccountName, ac.AccountDecomMode, ac.AccountDecomValue) = 1;
GO

CREATE OR ALTER PROCEDURE usp_Load_FactAccount
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @PrivCloudKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'PRIVCLOUD');
    DECLARE @SelfHostedKey INT = (SELECT SourceSystemKey FROM dim_source_system WHERE SourceSystemCode = 'SELFHOSTED');
    -- D-186: accounts in a safe matching the ignored-safe pattern aren't
    -- imported; ones already in BlueTrack drop out of the source rows
    -- below, so the load flags them deleted (history kept).
    DECLARE @IgnoreMode NVARCHAR(10), @IgnoreValue NVARCHAR(200);
    SELECT @IgnoreMode = SafeIgnoreMode, @IgnoreValue = SafeIgnoreValue FROM web.app_config;

    -- ---- Privilege Cloud ----
    MERGE fact_account AS tgt
    USING (
        SELECT
            @PrivCloudKey AS SourceSystemKey,
            a.AccountID AS SourceAccountId, a.AccountName, a.Address, a.UserName,
            plat.PlatformKey, sf.SafeKey,
            a.SecretType, a.AutoManaged, a.CPMStatus, a.ManualReason,
            a.LastCPMModified AS LastCPMModifiedDate, a.LastReconciled AS LastReconciledDate,
            a.LastVerified AS LastVerifiedDate, a.RemoteAccessRestricted,
            ISNULL(a.Deleted, 0) AS IsDeleted, a.Created AS CreatedDate, a.Platform_LogonDomain AS PlatformLogonDomain
        FROM stg_pc_accounts a
        LEFT JOIN dim_platform plat ON plat.SourceSystemKey = @PrivCloudKey AND plat.PlatformID = a.PlatformID
        LEFT JOIN dim_safe sf ON sf.SourceSystemKey = @PrivCloudKey AND sf.SafeName = a.SafeName
        WHERE dbo.fn_MatchesNamePattern(a.SafeName, @IgnoreMode, @IgnoreValue) = 0
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceAccountId = src.SourceAccountId
    WHEN MATCHED THEN
        UPDATE SET AccountName = src.AccountName, Address = src.Address, UserName = src.UserName,
                   PlatformKey = src.PlatformKey, SafeKey = src.SafeKey, SecretType = src.SecretType,
                   AutoManaged = src.AutoManaged, CPMStatus = src.CPMStatus, ManualReason = src.ManualReason,
                   LastCPMModifiedDate = src.LastCPMModifiedDate, LastReconciledDate = src.LastReconciledDate,
                   LastVerifiedDate = src.LastVerifiedDate, RemoteAccessRestricted = src.RemoteAccessRestricted,
                   IsDeletedInSource = src.IsDeleted, PlatformLogonDomain = src.PlatformLogonDomain
    -- D-184: an account the export already marks as deleted is never added;
    -- one BlueTrack already has is kept and flagged (WHEN MATCHED above).
    WHEN NOT MATCHED BY TARGET AND src.IsDeleted = 0 THEN
        INSERT (SourceSystemKey, SourceAccountId, AccountName, Address, UserName, PlatformKey, SafeKey,
                SecretType, AutoManaged, CPMStatus, ManualReason, LastCPMModifiedDate, LastReconciledDate,
                LastVerifiedDate, RemoteAccessRestricted, IsDeleted, CreatedDate, PlatformLogonDomain)
        VALUES (src.SourceSystemKey, src.SourceAccountId, src.AccountName, src.Address, src.UserName,
                src.PlatformKey, src.SafeKey, src.SecretType, src.AutoManaged, src.CPMStatus, src.ManualReason,
                src.LastCPMModifiedDate, src.LastReconciledDate, src.LastVerifiedDate, src.RemoteAccessRestricted,
                src.IsDeleted, src.CreatedDate, src.PlatformLogonDomain)
    -- an account present in fact_account for this source but absent from the
    -- latest staging snapshot means it no longer exists in the vault -- flag it
    WHEN NOT MATCHED BY SOURCE AND tgt.SourceSystemKey = @PrivCloudKey THEN
        UPDATE SET IsDeletedInSource = 1;

    -- ---- Self-Hosted ----
    ;WITH PivotedAccounts AS (
        SELECT
            f.CAFSafeID, f.CAFFileID, f.CAFSafeName,
            CAST(f.CAFSafeID AS NVARCHAR(50)) + '_' + CAST(f.CAFFileID AS NVARCHAR(50)) AS SourceAccountId,
            f.CAFFileName AS AccountName,
            f.CAFCreationDate AS CreatedDate,
            f.CAFModificationDate AS LastCPMModifiedDate,
            f.CAFLastUsedDate AS LastVerifiedDate,
            -- D-184: deleted when CAFDeletionDate is a real date: after the
            -- epoch placeholder some versions write (1970-01-01, or 1900 /
            -- 0001 defaults), and not before the account was created.
            CASE WHEN f.CAFDeletionDate >= '19700102'
                      AND (f.CAFCreationDate IS NULL OR f.CAFDeletionDate >= f.CAFCreationDate)
                 THEN 1 ELSE 0 END AS IsDeleted,
            -- PLACEHOLDER property names -- confirm against stg_sh_objectproperties before trusting
            MAX(CASE WHEN op.CAOPObjectPropertyName = 'UserName' THEN op.CAOPObjectPropertyValue END) AS UserName,
            MAX(CASE WHEN op.CAOPObjectPropertyName = 'Address'  THEN op.CAOPObjectPropertyValue END) AS Address,
            MAX(CASE WHEN op.CAOPObjectPropertyName = 'PolicyID' THEN op.CAOPObjectPropertyValue END) AS PolicyID
        FROM stg_sh_files f
        LEFT JOIN stg_sh_objectproperties op
               ON op.CAOPFileId = f.CAFFileID AND op.CAOPSafeId = f.CAFSafeID
        WHERE f.CAFType = 2   -- 'Password' per dim_selfhosted_code (CodeType 12, CodeValue 2)
          AND dbo.fn_MatchesNamePattern(f.CAFSafeName, @IgnoreMode, @IgnoreValue) = 0
        GROUP BY f.CAFSafeID, f.CAFFileID, f.CAFSafeName, f.CAFFileName,
                 f.CAFCreationDate, f.CAFModificationDate, f.CAFLastUsedDate, f.CAFDeletionDate
    )
    MERGE fact_account AS tgt
    USING (
        SELECT @SelfHostedKey AS SourceSystemKey, p.SourceAccountId, p.AccountName, p.Address, p.UserName,
               plat.PlatformKey, sf.SafeKey, p.CreatedDate, p.LastCPMModifiedDate, p.LastVerifiedDate, p.IsDeleted
        FROM PivotedAccounts p
        LEFT JOIN dim_safe sf ON sf.SourceSystemKey = @SelfHostedKey AND sf.SafeUrlId = CAST(p.CAFSafeID AS NVARCHAR(300))
        LEFT JOIN dim_platform plat ON plat.SourceSystemKey = @SelfHostedKey AND plat.PlatformID = p.PolicyID  -- will stay NULL until a Self-Hosted platform reference exists (see schema notes)
    ) AS src
        ON tgt.SourceSystemKey = src.SourceSystemKey AND tgt.SourceAccountId = src.SourceAccountId
    WHEN MATCHED THEN
        UPDATE SET AccountName = src.AccountName, Address = src.Address, UserName = src.UserName,
                   PlatformKey = src.PlatformKey, SafeKey = src.SafeKey,
                   LastCPMModifiedDate = src.LastCPMModifiedDate, LastVerifiedDate = src.LastVerifiedDate,
                   IsDeletedInSource = src.IsDeleted
    WHEN NOT MATCHED BY TARGET AND src.IsDeleted = 0 THEN
        INSERT (SourceSystemKey, SourceAccountId, AccountName, Address, UserName, PlatformKey, SafeKey,
                CreatedDate, LastCPMModifiedDate, LastVerifiedDate, IsDeleted)
        VALUES (src.SourceSystemKey, src.SourceAccountId, src.AccountName, src.Address, src.UserName,
                src.PlatformKey, src.SafeKey, src.CreatedDate, src.LastCPMModifiedDate, src.LastVerifiedDate, 0)
    WHEN NOT MATCHED BY SOURCE AND tgt.SourceSystemKey = @SelfHostedKey THEN
        UPDATE SET IsDeletedInSource = 1;

    -- D-185: IsDeleted -- the flag every list, report and view filters on --
    -- is deleted in CyberArk OR deleted in BlueTrack (web.account_deletion),
    -- so a BlueTrack delete survives the nightly load and an undelete
    -- returns the account to whatever CyberArk says.
    UPDATE fa
    SET IsDeleted = CASE WHEN fa.IsDeletedInSource = 1 OR ad.AccountKey IS NOT NULL THEN 1 ELSE 0 END
    FROM fact_account fa
    LEFT JOIN web.account_deletion ad ON ad.AccountKey = fa.AccountKey
    WHERE fa.SourceSystemKey IN (@PrivCloudKey, @SelfHostedKey)
      AND fa.IsDeleted <> CASE WHEN fa.IsDeletedInSource = 1 OR ad.AccountKey IS NOT NULL THEN 1 ELSE 0 END;
END
GO

PRINT '48_BlueTrack_DecommissionPatterns.sql complete.';
